### ISSUE TITLE
Device Agent cannot run Node-RED v3.1

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge-device-agent#173]
### Current Behavior

Node-RED 3.1 has a dependency of `got` at `12.6.0`

When starting `flowforge-device-agent`, the following error occurs:

```bash
[AGENT] 21/09/2023 14:19:33 [info] Starting Node-RED
[NR] 21/09/2023 14:19:33 [info] Error loading settings file: /opt/flowforge-device/project/settings.js
[NR] 21/09/2023 14:19:33 [info] Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/flowforge-device/project/node_modules/got/dist/source/index.js from /opt/flowforge-device/project/settings.js not supported.
[NR] 21/09/2023 14:19:33 [info] Instead change the require of index.js in /opt/flowforge-device/project/settings.js to a dynamic import() which is available in all CommonJS modules.
[NR] 21/09/2023 14:19:33 [info]     at Object.<anonymous> (/opt/flowforge-device/project/settings.js:5:26)
[NR] 21/09/2023 14:19:33 [info]     at Object.<anonymous> (/opt/flowforge-device/project/node_modules/node-red/red.js:140:20) {
[NR] 21/09/2023 14:19:33 [info]   code: 'ERR_REQUIRE_ESM'
[NR] 21/09/2023 14:19:33 [info] }
[AGENT] 21/09/2023 14:19:33 [info] Node
```

Where we are dependent upon `got v11-`

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by joepavitt** [comment]
Discovered on a screenshare when working with @hardillb

**Comment by joepavitt** [comment]
Devices that are not bound to an Instance, but instead an Application, have no way of defining which version of Node-RED to run. As such, they default to `latest`, see `package.json` produced for my device:

```
{
  "description": "Starter Snapshot - A starter snapshot for new applications",
  "private": true,
  "version": "0.0.0-0",
  "dependencies": {
    "node-red": "latest"
  }
}
```

**Comment by hardillb** [comment]
This is because the `settings.js` created by the device agent is loading the `got` library with `required()`. When it does this nodejs searches in the `node_modules` directory that is a sibling of the `settings.js` file, which in this case also contains the `node-red` install, which as noted at v3.1.0 includes got 12.x

This worked with NR 3.0.2 because it used got v11 (which works and matches the version the device agent depends on)

got v12 moved to only being a ESM module.

I'm not sure how to fix this to support both NR 3.0.2 and 3.1.0 at the moment

@Steve-Mcl any thoughts?

**Comment by Steve-Mcl** [comment]
I have been running device agent with 3.1.0 - most curious.

Will need to investigate what is different between versions / systems and why it works for me?

_WAIT_STOP_THINK_BEFORE_POST_
It may have been _before_ 3.1.0 became main stream 🤔

**Comment by hardillb** [comment]
I have test fix, will PR
